ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GmailConnection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrackedEmail" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrackedRecipient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrackedLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrackingEvent" ENABLE ROW LEVEL SECURITY;
